### ISSUE TITLE
start error in  init_datatables_mode()

### ISSUE THREAD

**Issue by caowencai** [CermakM/jupyter-datatables#17]
*

![image](https://user-images.githubusercontent.com/7457523/61621381-7429f980-aca5-11e9-9293-cb0b2ce44a6e.png)

**Comment by CermakM** [comment]
Uh, right ... It is installing the older version of [jupyter-require](https://github.com/CermakM/jupyter-require) ... It is still in pre-release, so it doesn't get installed by default.

I am gonna release the new stable ASAP, sorry for this. Meanwhile, manually installing the `jupyter-require` with `--pre` option should fix this.

**Comment by caowencai** [comment]
Fine at my windows, tks.
But still not work at CentOS jupyter-server

![image](https://user-images.githubusercontent.com/7457523/61677761-5014f980-ad33-11e9-8f5b-0833b5c82310.png)

**Comment by CermakM** [comment]
The [jupyter-require](https://pypi.org/project/jupyter-require/) v0.3.0 has already been released, so that should fix the first issue.

Ah, nice observation! This would probably be the pandas version. The `table_id` has been added to pandas in `0.23.0` according to the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_html.html). Please, check that you've got version `>=` to that one.

I am gonna add it to the requirement files.

**Comment by caowencai** [comment]
Get it.
Thank you~

**Comment by CermakM** [comment]
https://github.com/CermakM/jupyter-datatables/commit/a1573cfbcfab75380fcb79a6b82595f0aaac6c61 should fix this ... the patch has already been released as well.

Thanks for reporting!

Cheers,
Marek
